version: 2.1

commands:
  install_nodejs:
    description: Install Node.js 13.8.0
    steps:
      - run:
          name: Install Node.js 16.17.1
          command: |
            # Install Node.js LTS version as our base Node.js version
            curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
            sudo apt install -y nodejs
            # Use n version manager to use Node.js v13.8.0
            sudo npm install --global n
            sudo n 13.8.0
  
  install_docker:
    description: Install docker
    steps:
      - run:
          name: Install docker
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

  config_docker:
    description: login step with docker_hub account
    steps:
      - run: 
          command: docker login -u $DOCKERNAME -p $DOCKERPASS

jobs:

  build-img:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - install_nodejs
      - install_docker
      - run:
          name: build and tag img
          command: |
            docker build -t frontend:v1 .
            docker tag frontend:v1  waer
  push-img:
    docker: 
      - image: docker:17.05.0-ce-git
    steps:
      - config_docker
      - install_nodejs
      - install_docker
      - run:
          name: build and tag img
          command: |
            docker push waer/frontend



workflows:
  front-pipline:
    jobs:
      - build-img
      - push-img:
          requires: [build-img]


